### PR TITLE
Updated to 1.7.10

### PR DESCRIPTION
**Pull request by confuser**
Removed use of getOfflinePlayer within scoreboards. Fixed issue #5

Removed directory output specific path preventing other systems from
building

### CODE REVIEW

**Comment by confuser** [comment]
Appologies, it appears my other PR commit has ended up in here as well. I can re-do this if you like?

**Comment by instance01** [comment]
If I'm not mistaken this will not work on older minecraft versions, I had that planned to be added but you know, it wouldn't be compatible. Of course it has to be added some time as getOfflinePlayer lags in new versions, but about 40% of servers run on an older version than 1.7.10 (http://metrics.griefcraft.com/plugin/MinigamesLib), thus maybe a second branch for compatibility would be needed. I'll setup a branch for the old version in a minute and then pull your commits. No problem that the second one is included too. ;)

**Comment by instance01** [comment]
This also means that people on older minecraft versions should not get the automatical updates from bukkitdev, not sure how I'll solve that.

**Comment by confuser** [comment]
Good point. The API outputs which version the process is running, perhaps use that to decide which getScore method to use? For future proofing, perhaps create an abstracted scoreboard class that both arena scoreboard classes can use.

**Comment by instance01** [comment]
Alright I pulled your reset commit now, good work with it, thank you for contributing! Now regarding the scoreboard code, I decided to go with the reflection solution to provide compatibility for everyone. I'll close this pull request as soon as I got it done. :)

**Comment by instance01** [comment]
There we go ;) https://github.com/instance01/MinigamesAPI/commit/7070fe15b18af6ef96db33295e872e53b2b9df74

**Pull request closed without merging**
